# Generated by Django 4.1.5 on 2023-01-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_leavetype_remove_leaveapplication_leave_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='leave_type_id',
            new_name='leave_type',
        ),
    ]
