# Generated by Django 4.1.3 on 2023-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='leave_description',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
