# Generated by Django 4.1.5 on 2023-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_leavetype_leave_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='leavetype',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
